version: "3.9"

services:
  flask:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    ports:
      - "5000:5000"
    networks:
      - bridge
    depends_on:
      - postgres

  react:
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - bridge

  postgres:
    build:
      context: ./docker/postgres
    environment:
      - POSTGRES_PASSWORD=${DOCKER_PASSWORD}
      - POSTGRES_USER=${DOCKER_USERNAME}
      - POSTGRES_DB=${DOCKER_DATABASE}
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - bridge

  xwiki:
    image: xwiki:stable-postgres-tomcat
    environment:
      - DB_USER=xwiki
      - DB_PASSWORD=xwiki
      - DB_DATABASE=xwiki
      - DB_HOST=postgres
    ports:
      - "8080:8080"
    volumes:
      - xwiki:/usr/local/xwiki
    networks:
      - bridge
    depends_on:
      - postgres

volumes:
  postgres:
  xwiki:

networks:
  bridge:
    driver: bridge
