version: "3.9"

services:
  postgres:
    build:
      context: ./docker/postgres
    environment:
      - POSTGRES_PASSWORD=${DOCKER_PASSWORD}
      - POSTGRES_USER=${DOCKER_USERNAME}
      - POSTGRES_DB=${DOCKER_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - bridge

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DOCKER_USERNAME}@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=${DOCKER_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./docker/postgres/servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - bridge
    depends_on:
      - postgres

volumes:
  pgadmin:
  postgres:

networks:
  bridge:
