version: "3.9"

services:
  postgres:
    build:
      context: ./docker/postgres
    environment:
      - POSTGRES_PASSWORD=${DOCKER_PASSWORD}
      - POSTGRES_USER=${DOCKER_USERNAME}
      - POSTGRES_DB=${DOCKER_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - bridge

  flask:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    ports:
      - "5000:5000"
    networks:
      - bridge
    depends_on:
      - postgres

  react:
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - bridge

volumes:
  postgres:

networks:
  bridge:
