FROM python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/app/

COPY requirements.txt ./
RUN set -eux; \
        pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000
CMD gunicorn --preload --workers=2 --bind=0.0.0.0:5000 'app:create_app("production")'
